---
- hosts: all
  become: true
  pre_tasks:
    # make sure podman is installed
    - name: Install podman (RedHat, CentOS)
      ansible.builtin.dnf:
        name:
          - podman
        state: latest
  tasks:
    - name: Include role canary
      include_role:
        name: canary
