---
- name: Update sysctl to increase number of user namespaces
  ansible.posix.sysctl:
    name: user.max_user_namespaces
    value: 28633
    state: present
  become: true

- name: Create user for running the systemd container service
  ansible.builtin.user:
    name: "{{ CANARY_USER }}"
    state: present
    shell: /bin/bash
    uid: "{{ CANARY_USER_UID }}"
    groups: systemd-journal
    append: true
  become: true

- name: Enable user lingering for "non-interactive" DS_USER account
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ CANARY_USER }}"
  register: linger_var
  become: true
  changed_when: linger_var.rc == 0

- name: Allow port 21+ unpriv on host VM and reload Sysctl
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: 21
    state: present
  become: true

- name: Create canary dependency directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ CANARY_USER }}"
    group: "{{ CANARY_USER }}"
  loop:
    - "/home/{{ CANARY_USER }}"
    - "/home/{{ CANARY_USER }}/config"
    - "/home/{{ CANARY_USER }}/.config/containers/systemd/"

- name: Create canary env_file from template
  ansible.builtin.template:
    src: "roles/canary/templates/env_file.j2"
    dest: "/home/{{ CANARY_USER }}/env_file"
    owner: "{{ CANARY_USER }}"
    group: "{{ CANARY_USER }}"
    mode: u=rw,g=rw,o=r

- name: Create opencanary aaplication config file from template
  ansible.builtin.template:
    src: roles/canary/templates/opencanary.j2
    dest: "/home/{{ CANARY_USER }}/config/opencanary.conf"
    owner: "{{ CANARY_USER }}"
    group: "{{ CANARY_USER }}"
    mode: "0664"

- name: Create quadlet yaml file from template
  ansible.builtin.template:
    src: "roles/canary/templates/canary-yaml.j2"
    dest: "/home/{{ CANARY_USER }}/.config/containers/systemd/canary.yml"
    owner: "{{ CANARY_USER }}"
    group: "{{ CANARY_USER }}"
    mode: "0664"

- name: Create quadlet kube file from template
  ansible.builtin.template:
    src: "roles/canary/templates/canary-kube.j2"
    dest: "/home/{{ CANARY_USER }}/.config/containers/systemd/canary.kube"
    owner: "{{ CANARY_USER }}"
    group: "{{ CANARY_USER }}"
    mode: "0664"

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.command:
    cmd: "systemctl --user -M {{ CANARY_USER }}@ daemon-reload"
  become: true
  register: daemon_reload_var
  changed_when: daemon_reload_var.rc == 0

- name: Start canary.service
  ansible.builtin.command:
    cmd: "systemctl --user -M {{ CANARY_USER }}@ restart canary.service"
  become: true
  register: canary_service_var
  changed_when: canary_service_var.rc == 0
